name: Cppcheck
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  cpp_check:
    runs-on: [self-hosted, vm, ubuntu-current]
    name: Cppcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Compile Commands
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@" -B cmake_build
      - name: Cppcheck
        run: cppcheck --project=cmake_build/compile_commands.json -j$(nproc) -i resolve_symlinks/ -i src/plumr/protobuf -i test -i cmake_build/_deps --suppress=unknownMacro --suppress="preprocessorErrorDirective"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
