name: Aarch64 Linux Musl
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  cross-compile:
    timeout-minutes: 45
    strategy:
      fail-fast: false
    runs-on: [self-hosted, vm, ubuntu-current]
    name: Raspberry Pi Cross-compile
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Clone toolchains
        run: rm -rf ~/toolchains && git clone --depth 1 git@github.com:steinwurf/cmake-toolchains.git ~/toolchains
      - name: CMake Cleanup
        run: cmake -E remove_directory cmake_build
      - name: CMake Configure
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cmake -B cmake_build -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS" -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_BUILD_TYPE=WurfRelease -DCMAKE_TOOLCHAIN_FILE=~/toolchains/zig-toolchain-aarch64-linux-musl.cmake -GNinja
      - name: CMake Build
        run: cmake --build cmake_build -j$(( ( $(nproc) + 1 ) / 2 ))
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
