name: Valgrind
"on":
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
  pull_request:
jobs:
  valgrind:
    timeout-minutes: 45
    name: Valgrind 3.19.0
    runs-on: [self-hosted, vm, ubuntu-current]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        env:
          EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: python3 waf configure --git_protocol=git@ ${{ env.EXTRA_RESOLVE_OPTIONS }} 
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
